### IP address and port to listen to, e.g. "[::]:5050" (IPv4 and IPv4)
listenport      = "[::]:5050"

### Secret (must match the one in prosody.conf.lua!)
secret          = "secret"

### Where to store the uploaded files
storeDir        = "./uploads/"

### Subdirectory for HTTP upload / download requests (usually "upload/")
uploadSubDir    = "upload/"
